### PR TITLE
Deprecate `scrapy.twisted_version`

### PR DESCRIPTION
**Pull request by Laerte**
fix: #6509

### CODE REVIEW

File: scrapy/__init__.py [hunk 1]
```diff
@@ -30,13 +26,22 @@
 # Scrapy and Twisted versions
 __version__ = (pkgutil.get_data(__package__, "VERSION") or b"").decode("ascii").strip()
 version_info = tuple(int(v) if v.isdigit() else v for v in __version__.split("."))
-twisted_version = (_txv.major, _txv.minor, _txv.micro)
 
 
-# Ignore noisy twisted deprecation warnings
-warnings.filterwarnings("ignore", category=DeprecationWarning, module="twisted")
```
Comment (Laerte) [inline scrapy/__init__.py:37]: For some reason if I add this piece I get duplicated deprecation warning message, also not sure where should I place a test for this change.

Comment (wRAR) [reply scrapy/__init__.py:37]: > if I add this piece I get duplicate deprecation warning message

Can you show an example?

I think this line shouldn't be removed, though it's probably not that useful, as IIRC `DeprecationWarning` warnings aren't printed anywhere by default.

**Comment by wRAR** [comment]
No idea what do these pytest errors mean.

File: scrapy/__init__.py (hunk 1 above)
Comment (Laerte) [reply scrapy/__init__.py:37]: Sure, add the removed line after the warnings import and then call this snippet:

```python
from scrapy import twisted_version
print(twisted_version)
```

Comment (Laerte) [reply scrapy/__init__.py:37]: Now i'm trying to figure out why tests are failing after I added ``__getattr__`` method. 😅

**Comment by Laerte** [comment]
> No idea what do these pytest errors mean.

So because we defined ``__getattr__``
 the default behavior is to raise a `AttributeError` exception but It was returning None instead, that's why was failing, fixed.

Ref: https://github.com/pytest-dev/pytest/issues/4631

File: scrapy/__init__.py [hunk 2]
```diff
@@ -30,13 +26,24 @@
...
+
+        from scrapy.exceptions import ScrapyDeprecationWarning
+
+        warnings.warn(
+            "The scrapy.twisted_version attribute is deprecated, use twisted.version instead",
+            ScrapyDeprecationWarning,
+        )
+        return _txv.major, _txv.minor, _txv.micro
+
+    raise AttributeError
```
Comment (Laerte) [inline scrapy/__init__.py:45]: Wondering since this a module not a class if we should raise `ImportError` instead.

**Comment by Laerte** [comment]
@wRAR Added tests for test coverage

File: scrapy/__init__.py (hunk 2 above)
Comment (Laerte) [reply scrapy/__init__.py:45]: Tried that, don't work. 😄

File: scrapy/__init__.py (hunk 1 above)
Comment (Laerte) [reply scrapy/__init__.py:37]: Got it, fixed.

File: scrapy/__init__.py [hunk 3]
```diff
@@ -30,13 +26,27 @@
...
 
 
-# Ignore noisy twisted deprecation warnings
-warnings.filterwarnings("ignore", category=DeprecationWarning, module="twisted")
+def __getattr__(name: str):
+    if name == "twisted_version":
+        import warnings
+
+        # Ignore noisy twisted deprecation warnings
+        warnings.filterwarnings("ignore", category=DeprecationWarning, module="twisted")
```
Comment (wRAR) [inline scrapy/__init__.py:36]: I think the reason for this line is to be executed before any Scrapy code, so that the user doesn't see those warnings. It was there before `from twisted import version` was even added.

Comment (Laerte) [reply scrapy/__init__.py]: Pushed the rollback to original code.

**Comment by Gallaecio** [comment]
```
scrapy/pipelines/media.py:209: error: Cannot assign to a method  [method-assign]
```

**Comment by Gallaecio** [comment]
> ```
> scrapy/pipelines/media.py:209: error: Cannot assign to a method  [method-assign]
> ```

Nevermind, it seems that might have been introduced by https://github.com/scrapy/scrapy/pull/6510.

**Review by Gallaecio — APPROVED** [review]

**Review by wRAR — APPROVED** [review]

**Comment by wRAR** [comment]
Thanks!
