### ISSUE TITLE
Impossible to subclass scrapy.core.downloader.Downloader: 'module' object has no attribute 'downloader'

### ISSUE THREAD

**Issue by Djayb6** [scrapy/scrapy#1458]
On scrapy 0.24.6 I successfully subclassed the default's downloader like so: 
```python
import scrapy
from scrapy.utils.httpobj import urlparse_cached


class WebsiteDownloader(scrapy.core.downloader.Downloader):

    def _get_slot_key(self, request, spider):
        if 'download_slot' in request.meta:
            return request.meta['download_slot']

        return request.meta['website_id'] if not request.meta.get('social_request') \
            else urlparse_cached(request).hostname or ''
```

However when I updated scrapy to 1.0.3, I got the following error:

```python
File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 65, in __init__
    downloader_cls = load_object(self.settings['DOWNLOADER'])
  File "/usr/local/lib/python2.7/site-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/me/dev/spider/downloader.py", line 7, in <module>
    class WebsiteDownloader(scrapy.core.downloader.Downloader):
exceptions.AttributeError: 'module' object has no attribute 'downloader'
```

Woudl I have an idea of what's going on ? Thank you

**Comment by Youwotma** [comment]
Hi! Sounds like you forgot to `import scrapy.core.downloader` :)

**Comment by kmike** [comment]
I think @Youwotma is right; `scrapy.core.__init__` was not changed since 2009, so downloader was never exposed as a 'downloader' attribute of `scrapy.core` (without an import).

**Comment by Djayb6** [comment]
That’s crazy, I swear it worked as is before upgrading to 1.0.3 (I double checked with my private repo). I changed the way the import is done anyway. Thanks.

**Comment by Karla-Isabel-Sandoval** [comment]
Scrappy has worked well for me with the exception of site errors.
When using `scapy crawl reed`, reed is the name of my spider I came across similar error messages: 

`~/o/j/j/jobboardcomposition $ scrapy crawl reed
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 141, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 238, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 129, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 325, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/usr/local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 33, in from_settings
    return cls(settings)
  File "/usr/local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 20, in __init__
    self._load_all_spiders()
  File "/usr/local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 28, in _load_all_spiders
    for module in walk_modules(name):
  File "/usr/local/lib/python2.7/site-packages/scrapy/utils/misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Hyacinth/onapply/jobboardcomposition/jobboardcomposition/jobboardcomposition/spiders/reed.py", line 18
    filename =
             ^
SyntaxError: invalid syntax
~/o/`


@Youwotma thanks for suggesting the use of `import scrapy.core.downloader` is it best to include it in the items.py folder? If it doesn't belong there could you suggest where?
Thanks in advanced.

**Comment by Karla-Isabel-Sandoval** [comment]
Just downloaded Site-map-generator 0.3.9, https://pypi.python.org/pypi/sitemap-generator/ , which is made for python 2.7.9 - let's see if it makes a diff.
