### ISSUE TITLE
an error import in scrapy/core/downloader/handlers/http11.py

### ISSUE THREAD

**Issue by zonglinyue** [scrapy/scrapy#2487]
an error import at line 16 is  that 
"from twisted.web.client import Agent, ProxyAgent, ResponseDone, \
    HTTPConnectionPool"
there's none class or method in twisted.web.client named  HTTPConnectionPool,is it "HTTP11ClientProtocol" in "twisted.web._newclient" or "HTTPConnectionPool" in "urllib3"

**Comment by redapple** [comment]
Hello @zonglinyue ,
can you share the whole traceback of the error? (all the text lines in your console before that `ImportError`)
Also, can you tell us which system you're on? (Windows, Linux variant, OSX etc.)
And how you are installing scrapy? and the output of `pip freeze` if you are using `pip`?

**Comment by zonglinyue** [comment]
my system is windows10,python2.7,scrapy1.3.0,and scrapy installed scrapy by pip.  
there's  error log in console
`2017-01-10 16:01:00 [common] DEBUG: Reading URLs from redis list 'common:task'
2017-01-10 16:01:00 [py.warnings] WARNING: D:\WorkSpaces\Pycharm\spider\e23yq\scrapy_redis\dupefilter.py:2: ScrapyDeprecationWarning: Module `scrapy.dupefilter` is deprecated, use `scrapy.dupefilters` instead
  from scrapy.dupefilter import BaseDupeFilter

2017-01-10 16:01:00 [py.warnings] WARNING: d:\programs\python\python27\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

2017-01-10 16:01:00 [py.warnings] WARNING: D:\WorkSpaces\Pycharm\spider\e23yq\downloadmiddleware\useragent.py:5: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.useragent` is deprecated, use `scrapy.downloadermiddlewares.useragent` instead
  from scrapy.contrib.downloadermiddleware.useragent import UserAgentMiddleware

2017-01-10 16:01:01 [twisted] ERROR: Unhandled error in Deferred:
Unhandled error in Deferred:
2017-01-10 16:01:01 [twisted] ERROR: Unhandled Error
Traceback (most recent call last):
  File "d:\programs\python\python27\lib\site-packages\scrapy\commands\runspider.py", line 87, in run
    self.crawler_process.crawl(spidercls, **opts.spargs)
  File "d:\programs\python\python27\lib\site-packages\scrapy\crawler.py", line 163, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "d:\programs\python\python27\lib\site-packages\scrapy\crawler.py", line 167, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "d:\programs\python\python27\lib\site-packages\twisted\internet\defer.py", line 1187, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "d:\programs\python\python27\lib\site-packages\twisted\internet\defer.py", line 1045, in _inlineCallbacks
    result = g.send(result)
  File "d:\programs\python\python27\lib\site-packages\scrapy\crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "d:\programs\python\python27\lib\site-packages\scrapy\crawler.py", line 72, in crawl
    self.engine = self._create_engine()
  File "d:\programs\python\python27\lib\site-packages\scrapy\crawler.py", line 97, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "d:\programs\python\python27\lib\site-packages\scrapy\core\engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "d:\programs\python\python27\lib\site-packages\scrapy\core\downloader\__init__.py", line 88, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "d:\programs\python\python27\lib\site-packages\scrapy\middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "d:\programs\python\python27\lib\site-packages\scrapy\middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "d:\programs\python\python27\lib\site-packages\scrapy\utils\misc.py", line 44, in load_object
    mod = import_module(module)
  File "d:\programs\python\python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "d:\programs\python\python27\lib\site-packages\scrapy\downloadermiddlewares\retry.py", line 24, in <module>
    from scrapy.core.downloader.handlers.http11 import TunnelError
  File "d:\programs\python\python27\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 16, in <module>
    from twisted.web.client import Agent, ProxyAgent, ResponseDone, \
exceptions.ImportError: cannot import name HTTPConnectionPool

Unhandled Error`

**Comment by redapple** [comment]
What version of Twisted do you have on your system?

**Comment by zonglinyue** [comment]
Twisted  version is 16.5.0,and it's no HTTPConnectionPool in "twisted.web.client"
https://github.com/twisted/twisted/blob/twisted-16.5.0/src/twisted/web/client.py

**Comment by redapple** [comment]
Sorry, I'm not following, I see `HTTPConnectionPool` there: https://github.com/twisted/twisted/blob/twisted-16.5.0/src/twisted/web/client.py#L1178
```
class HTTPConnectionPool(object):
    """
    A pool of persistent HTTP connections.
```

**Comment by zonglinyue** [comment]
e, i replaced the client.py,an there a new error:
  File "d:\programs\python\python27\lib\site-packages\twisted\web\client.py", line 30, in <module>
    from twisted.python.compat import _PY3, networkString
exceptions.ImportError: cannot import name _PY3
would you tell me which version of Twisted wil work well with scrapy 1.3.0?

**Comment by redapple** [comment]
There's probably something wrong with your installation, especially with Twisted,
because Twisted 16.5 works fine with Scrapy 1.3.0 as far as I can test (I'm on Linux though):

```
$ mkvirtualenv scrapy13-twisted.16.5
New python executable in /home/paul/.virtualenvs/scrapy13-twisted.16.5/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /home/paul/.virtualenvs/scrapy13-twisted.16.5/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/paul/.virtualenvs/scrapy13-twisted.16.5/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/paul/.virtualenvs/scrapy13-twisted.16.5/bin/preactivate
virtualenvwrapper.user_scripts creating /home/paul/.virtualenvs/scrapy13-twisted.16.5/bin/postactivate
virtualenvwrapper.user_scripts creating /home/paul/.virtualenvs/scrapy13-twisted.16.5/bin/get_env_details
(scrapy13-twisted.16.5) paul@host:~$ pip install twisted==16.5
Collecting twisted==16.5
Collecting constantly>=15.1 (from twisted==16.5)
  Using cached constantly-15.1.0-py2.py3-none-any.whl
Collecting zope.interface>=3.6.0 (from twisted==16.5)
Collecting incremental>=16.10.1 (from twisted==16.5)
  Using cached incremental-16.10.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./.virtualenvs/scrapy13-twisted.16.5/lib/python2.7/site-packages (from zope.interface>=3.6.0->twisted==16.5)
Installing collected packages: constantly, zope.interface, incremental, twisted
Successfully installed constantly-15.1.0 incremental-16.10.1 twisted-16.5.0 zope.interface-4.3.3
(scrapy13-twisted.16.5) paul@host:~$ pip install scrapy
Collecting scrapy
  Using cached Scrapy-1.3.0-py2.py3-none-any.whl
Collecting parsel>=0.9.5 (from scrapy)
  Using cached parsel-1.1.0-py2.py3-none-any.whl
Collecting lxml (from scrapy)
  Downloading lxml-3.7.2-cp27-cp27mu-manylinux1_x86_64.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 165kB/s 
Collecting pyOpenSSL (from scrapy)
  Using cached pyOpenSSL-16.2.0-py2.py3-none-any.whl
Collecting queuelib (from scrapy)
  Using cached queuelib-1.4.2-py2.py3-none-any.whl
Collecting service-identity (from scrapy)
  Using cached service_identity-16.0.0-py2.py3-none-any.whl
Collecting w3lib>=1.15.0 (from scrapy)
  Using cached w3lib-1.16.0-py2.py3-none-any.whl
Requirement already satisfied: Twisted>=13.1.0 in ./.virtualenvs/scrapy13-twisted.16.5/lib/python2.7/site-packages (from scrapy)
Collecting PyDispatcher>=2.0.5 (from scrapy)
Collecting six>=1.5.2 (from scrapy)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting cssselect>=0.9 (from scrapy)
  Using cached cssselect-1.0.0-py2.py3-none-any.whl
Collecting cryptography>=1.3.4 (from pyOpenSSL->scrapy)
Collecting attrs (from service-identity->scrapy)
  Using cached attrs-16.3.0-py2.py3-none-any.whl
Collecting pyasn1-modules (from service-identity->scrapy)
  Using cached pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting pyasn1 (from service-identity->scrapy)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Requirement already satisfied: constantly>=15.1 in ./.virtualenvs/scrapy13-twisted.16.5/lib/python2.7/site-packages (from Twisted>=13.1.0->scrapy)
Requirement already satisfied: zope.interface>=3.6.0 in ./.virtualenvs/scrapy13-twisted.16.5/lib/python2.7/site-packages (from Twisted>=13.1.0->scrapy)
Requirement already satisfied: incremental>=16.10.1 in ./.virtualenvs/scrapy13-twisted.16.5/lib/python2.7/site-packages (from Twisted>=13.1.0->scrapy)
Collecting idna>=2.0 (from cryptography>=1.3.4->pyOpenSSL->scrapy)
  Using cached idna-2.2-py2.py3-none-any.whl
Collecting enum34 (from cryptography>=1.3.4->pyOpenSSL->scrapy)
  Using cached enum34-1.1.6-py2-none-any.whl
Requirement already satisfied: setuptools>=11.3 in ./.virtualenvs/scrapy13-twisted.16.5/lib/python2.7/site-packages (from cryptography>=1.3.4->pyOpenSSL->scrapy)
Collecting ipaddress (from cryptography>=1.3.4->pyOpenSSL->scrapy)
  Using cached ipaddress-1.0.17-py2-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=1.3.4->pyOpenSSL->scrapy)
  Using cached cffi-1.9.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.3.4->pyOpenSSL->scrapy)
Installing collected packages: six, w3lib, cssselect, lxml, parsel, pyasn1, idna, enum34, ipaddress, pycparser, cffi, cryptography, pyOpenSSL, queuelib, attrs, pyasn1-modules, service-identity, PyDispatcher, scrapy
Successfully installed PyDispatcher-2.0.5 attrs-16.3.0 cffi-1.9.1 cryptography-1.7.1 cssselect-1.0.0 enum34-1.1.6 idna-2.2 ipaddress-1.0.17 lxml-3.7.2 parsel-1.1.0 pyOpenSSL-16.2.0 pyasn1-0.1.9 pyasn1-modules-0.0.8 pycparser-2.17 queuelib-1.4.2 scrapy-1.3.0 service-identity-16.0.0 six-1.10.0 w3lib-1.16.0
(scrapy13-twisted.16.5) paul@host:~$ scrapy shell https://scrapy.org
2017-01-10 11:29:04 [scrapy.utils.log] INFO: Scrapy 1.3.0 started (bot: scrapybot)
2017-01-10 11:29:04 [scrapy.utils.log] INFO: Overridden settings: {'LOGSTATS_INTERVAL': 0, 'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter'}
2017-01-10 11:29:04 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2017-01-10 11:29:04 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-01-10 11:29:04 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-01-10 11:29:04 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2017-01-10 11:29:04 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2017-01-10 11:29:04 [scrapy.core.engine] INFO: Spider opened
2017-01-10 11:29:04 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://scrapy.org> (referer: None)
[s] Available Scrapy objects:
[s]   scrapy     scrapy module (contains scrapy.Request, scrapy.Selector, etc)
[s]   crawler    <scrapy.crawler.Crawler object at 0x7f24be1da950>
[s]   item       {}
[s]   request    <GET https://scrapy.org>
[s]   response   <200 https://scrapy.org>
[s]   settings   <scrapy.settings.Settings object at 0x7f24be1da9d0>
[s]   spider     <DefaultSpider 'default' at 0x7f24b9ca31d0>
[s] Useful shortcuts:
[s]   fetch(url[, redirect=True]) Fetch URL and update local objects (by default, redirects are followed)
[s]   fetch(req)                  Fetch a scrapy.Request and update local objects 
[s]   shelp()           Shell help (print this help)
[s]   view(response)    View response in a browser
>>> 
(scrapy13-twisted.16.5) paul@host:~$ pip freeze
attrs==16.3.0
cffi==1.9.1
constantly==15.1.0
cryptography==1.7.1
cssselect==1.0.0
enum34==1.1.6
idna==2.2
incremental==16.10.1
ipaddress==1.0.17
lxml==3.7.2
parsel==1.1.0
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.17
PyDispatcher==2.0.5
pyOpenSSL==16.2.0
queuelib==1.4.2
Scrapy==1.3.0
service-identity==16.0.0
six==1.10.0
Twisted==16.5.0
w3lib==1.16.0
zope.interface==4.3.3
```

Given the problems people have with installing Scrapy on Windows, we recommend using Anaconda/Miniconda. See https://docs.scrapy.org/en/latest/intro/install.html#anaconda

You can also [use a virtualenv](https://docs.scrapy.org/en/latest/intro/install.html#using-a-virtual-environment-recommended) to isolate your packages so as not to mess with your system packages.

**Comment by zonglinyue** [comment]
it may caused by Twisted16.5.0 i'd used.Ctrl+F to search  HTTPConnectionPool in twisted.web.client have no found before i replace it,and after i replaced it there' another problem.i've upgrade Twisted to 16.6.0,and it can work now.
Thank you !

**Comment by redapple** [comment]
Thanks for the heads up!
Happy scraping
