### ISSUE TITLE
Parse commando doesn't work without specifying concrete spider

### ISSUE THREAD

**Issue by enagorny** [scrapy/scrapy#209]
It worked in 0.14.
STR:
scrapy parse "http://www.example.com/foobar" -c parse_item

And now it throws exception:

```
Traceback (most recent call last):
File "/usr/local/bin/scrapy", line 4, in <module>
  execute()
File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 131, in execute
  _run_print_help(parser, _run_command, cmd, args, opts)
File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 76, in _run_print_help
  func(*a, **kw)
File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 138, in _run_command
  cmd.run(args, opts)
File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/parse.py", line 194, in run
  self.set_spider(url, opts)
File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/parse.py", line 128, in set_spider
  self.spider = create_spider_for_request(self.crawler.spiders, url)
File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/spider.py", line 38, in create_spider_for_request
  snames = spidermanager.find_by_request(request)
File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermanager.py", line 48, in find_by_request
  if cls.handles_request(request)]
File "/usr/local/lib/python2.7/dist-packages/scrapy/spider.py", line 62, in handles_request
  return url_is_from_spider(request.url, cls)
AttributeError: 'str' object has no attribute 'url'
```
