### ISSUE TITLE
Flake8 build error in Travis

### ISSUE THREAD

**Issue by elacuesta** [scrapy/scrapy#4570]
Flake8 checks are currently failing with the following for all files:
```
.tox/flake8/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
.tox/flake8/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
.tox/flake8/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
.tox/flake8/lib/python3.8/site-packages/_pytest/runner.py:134: in pytest_runtest_call
    item.runtest()
.tox/flake8/lib/python3.8/site-packages/pytest_flake8.py:119: in runtest
    found_errors, out, err = call(
.tox/flake8/lib/python3.8/site-packages/py/_io/capture.py:150: in call
    res = func(*args, **kwargs)
.tox/flake8/lib/python3.8/site-packages/pytest_flake8.py:191: in check_file
    app.parse_preliminary_options_and_args(args)
E   AttributeError: 'Application' object has no attribute 'parse_preliminary_options_and_args'
```

Failed builds:
* https://travis-ci.org/github/scrapy/scrapy/jobs/686060612
* https://travis-ci.org/github/scrapy/scrapy/jobs/685973155

I suspect there might have been some change in a recent release of `pytest-flake8`, and pinning the version would solve the problem.

**Comment by elacuesta** [comment]
Comparing with a few successful builds, pytest-flake8 is the same (version 1.0.5), the difference seems to be with Flake8 (works with 3.7.9, fails with 3.8.1)

**Comment by elacuesta** [comment]
Already reported in the Flake8 repo: https://gitlab.com/pycqa/flake8/-/issues/640

**Comment by noviluni** [comment]
Hi @elacuesta This can be fixed by pinning `flake8<3.8`. 

The issue is related to the `pytest-flake8` plugin and I already did a PR that fixes it: https://github.com/tholo/pytest-flake8/pull/68/

**Comment by elacuesta** [comment]
Yup, I was evaluating if we should pin flake8 or wait for an upstream fix to arrive. Nice work on the fix!

**Comment by noviluni** [comment]
It seems fixed :tada: 

Passing PR: https://github.com/scrapy/scrapy/pull/4572

**Comment by Gallaecio** [comment]
Indeed, great work.
