### ISSUE TITLE
Installation fails on Void Linux

### ISSUE THREAD

**Issue by Vintodrimmer** [scrapy/scrapy#3242]
Good day,

I'm trying to install Scrapy for Python3, using `pip install --user scrapy`. This results in the following error:
```
       { result = SSL_set_mode(x0, x1); }
                  ^~~~~~~~~~~~
    build/temp.linux-x86_64-3.6/_openssl.c:52849:14: warning: conversion to 'long unsigned int' from 'long int' may change the sign of the result [-Wsign-conversion]
    build/temp.linux-x86_64-3.6/_openssl.c: In function '_cffi_d_SSL_set_options':
    build/temp.linux-x86_64-3.6/_openssl.c:52862:10: warning: conversion to 'long int' from 'long unsigned int' may change the sign of the result [-Wsign-conversion]
       return SSL_set_options(x0, x1);
              ^~~~~~~~~~~~~~~
    build/temp.linux-x86_64-3.6/_openssl.c:52862:10: warning: conversion to 'long unsigned int' from 'long int' may change the sign of the result [-Wsign-conversion]
    build/temp.linux-x86_64-3.6/_openssl.c: In function '_cffi_f_SSL_set_options':
    build/temp.linux-x86_64-3.6/_openssl.c:52895:14: warning: conversion to 'long int' from 'long unsigned int' may change the sign of the result [-Wsign-conversion]
       { result = SSL_set_options(x0, x1); }
                  ^~~~~~~~~~~~~~~
    build/temp.linux-x86_64-3.6/_openssl.c:52895:14: warning: conversion to 'long unsigned int' from 'long int' may change the sign of the result [-Wsign-conversion]
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-21gspbgp/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-t8vxql47-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-21gspbgp/cryptography/

```

I have installed following packages:
* python3-devel
* libffi-devel
* libxml2-devel
* libressl-devel
* libxslt-devel
* zlib-devel

May that be because of libreSSL?

**Comment by wRAR** [comment]
The log shows the `cryptography` module is being built, so this is not a scrapy problem. Also, you didn't include the actual compilation error in your trimmed output, only some later warnings.

**Comment by Vintodrimmer** [comment]
What may be the cause of the problem?

Here's the [complete output](https://pastebin.com/L5sxSUVx) of `pip install --user scrapy`.

It does say 
> Running setup.py install for cryptography: finished with status 'error'

**Comment by msdos** [comment]
You should try to install `cryptography` alone. If there's no error, this issue makes some sense and people here can try to figure it out what happened; If not, you should open an issue at `cryptography` package and close this one.

**Comment by Vintodrimmer** [comment]
It doesn't install, @msdos.

Thanks for the pointer.

**Comment by Vintodrimmer** [comment]
My issue was with `cryptography` package and was solved by updating to LibreSSL 2.7.3.
`cryptography` guys are working on a patch for 2.7.2, but I'm not sure when it will be ready.
