### ISSUE TITLE
scrapy shell raising an exception with iPython 0.11

### ISSUE THREAD

**Issue by dchaplinsky** [scrapy/scrapy#43]
```
2011-10-04 11:33:47+0200 [scrapy] ERROR: Shell error
        Traceback (most recent call last):
          File "/usr/lib/python2.6/threading.py", line 504, in __bootstrap
            self.__bootstrap_inner()
          File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
            self.run()
          File "/usr/lib/python2.6/threading.py", line 484, in run
            self.__target(*self.__args, **self.__kwargs)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.6/dist-packages/twisted/python/threadpool.py", line 207, in _worker
            result = context.call(ctx, function, *args, **kwargs)
          File "/usr/local/lib/python2.6/dist-packages/twisted/python/context.py", line 59, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/local/lib/python2.6/dist-packages/twisted/python/context.py", line 37, in callWithContext
            return func(*args,**kw)
          File "/usr/local/lib/python2.6/dist-packages/scrapy/shell.py", line 56, in _start
            start_python_console(self.vars)
          File "/usr/local/lib/python2.6/dist-packages/scrapy/utils/console.py", line 14, in start_python_console
            shell = IPython.Shell.IPShellEmbed(argv=[], user_ns=namespace)
        exceptions.AttributeError: 'module' object has no attribute 'Shell'
```

However, works fine with 0.10.1
