### ISSUE TITLE
Accessing crawler from log before crawler is assigned to spider

### ISSUE THREAD

**Issue by rocioar** [scrapy/scrapy#881]
Bug introduced in commit https://github.com/scrapy/scrapy/commit/d513b5a542f5581a60a10200e07b58ec294caea5

Traceback:

```python
File "/Library/Python/2.7/site-packages/Scrapy-0.25.1-py2.7.egg/scrapy/log.py", line 53, in _emit_with_crawler
	    ev = self._emit(eventDict)
	  File "/Library/Python/2.7/site-packages/Scrapy-0.25.1-py2.7.egg/scrapy/log.py", line 47, in _emit
	    self.crawler)
	  File "/Library/Python/2.7/site-packages/Scrapy-0.25.1-py2.7.egg/scrapy/log.py", line 83, in _adapt_eventdict
	    if crawler and (not spider or spider.crawler is not crawler):
	exceptions.AttributeError: 'TestSpider' object has no attribute 'crawler'
```
